routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', 'App\Http\Controllers\HomeController@index')->name('home');
// Auth::routes();

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return redirect('/');
})->name('dashboard');

// route users
Route::resource('users', 'App\Http\Controllers\UsersController');    
Route::get('/users/delete/{id}', 'App\Http\Controllers\UsersController@destroy');

// route user_types
Route::resource('user_types', 'App\Http\Controllers\UserTypesController');    
Route::get('/user_types/delete/{id}', 'App\Http\Controllers\UserTypesController@destroy');

// route meetings
Route::resource('meetings', 'App\Http\Controllers\MeetingsController');    
Route::get('/meetings/delete/{id}', 'App\Http\Controllers\MeetingsController@destroy');
Route::get('/meetings/create_document_meetings/{id}', 'App\Http\Controllers\MeetingsController@create_document_meetings');
Route::post('/meetings/create_document_meetings', 'App\Http\Controllers\MeetingsController@store_document_meetings');
Route::post('/meetings/update_document_report', 'App\Http\Controllers\MeetingsController@update_document_report');
Route::get("/meetings/download_document_meetings/{id}", "App\Http\Controllers\MeetingsController@download_document_meetings");
Route::get("/meetings/delete_meeting_document/{id}", "App\Http\Controllers\MeetingsController@delete_meeting_document");
Route::get('/meetings/{id}/export_excel', 'App\Http\Controllers\MeetingsController@export_excel');
Route::get("/meetings/download_document_report/{id}", "App\Http\Controllers\MeetingsController@download_document_report");

// route meetings
Route::resource('meeting_agendas', 'App\Http\Controllers\MeetingAgendasController');    
Route::get('/meeting_agendas/delete/{id}', 'App\Http\Controllers\MeetingAgendasController@destroy');

// route Comments
Route::resource('comments', 'App\Http\Controllers\CommentsController');    
Route::get('/comments/delete/{id}', 'App\Http\Controllers\CommentsController@destroy');
Route::post('/comments/update_meeting_agenda', 'App\Http\Controllers\CommentsController@update_meeting_agenda');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Fortify\TwoFactorAuthenticatable;
use Laravel\Jetstream\HasProfilePhoto;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens;
    use HasFactory;
    use HasProfilePhoto;
    use Notifiable;
    use TwoFactorAuthenticatable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
        'two_factor_recovery_codes',
        'two_factor_secret',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * The accessors to append to the model's array form.
     *
     * @var array
     */
    protected $appends = [
        'profile_photo_url',
    ];

    public function user_type()
    {
        return $this->belongsTo('App\Models\UserType', 'user_type_id');
    }
}

app/Models/UserType.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class UserType extends Model
{
    use HasFactory;
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\User;
use App\Models\UserType;
use File;

class UsersController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::all();
        return view("users.index",compact(["users"]));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $user_types = UserType::all();
        return view("users.create",compact(["user_types"]));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $input = $request->all();

        $user = new User;
        $user->name = $input['name'];
        $user->user_type_id = $input['user_type_id'];
        $user->email = $input['email'];
        $user->password = bcrypt($input['password']);
        if ($request->file('image')) {
            $files = $input['image'];
            if ($files) {
                $destinationPath    = 'uploads/attachment/users/'; // The destination were you store the document.
                if(!(file_exists(public_path('/uploads/attachment/users/'))))
                {
                    File::makeDirectory($destinationPath, $mode = 0777, true, true);
                }
                $filename           = $files->getClientOriginalName(); // Original file name that the end user used for it.
                $mime_type          = $files->getMimeType(); // Gets this example image/png
                $extension          = $files->getClientOriginalExtension(); // The original extension that the user used example .jpg or .png.
                $filename           = time().'-'.$filename; // random file name to replace original
                $upload_success     = $files->move($destinationPath, $filename); // Now we move the file to its new home.
                $user->image = $destinationPath.'/'.$filename;
            }
        }
        $user->save();
        \Session::flash('success','User berhasil dibuat');
        return redirect("users/");
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user_types = UserType::all();
        $user = User::find($id);
        return view("users.edit",compact(["user", "user_types"]));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $input = $request->all();
        $user = User::find($input["id"]);
        $user->name = $input["name"];
        $user->user_type_id = $input['user_type_id'];
        $user->email = $input["email"];
        if (!empty($input["password"])) {
            $user->password = bcrypt($input["password"]);
        }
        if ($request->file('image')) {
            if(!is_null($user->image)){
                unlink($user->image);                
            }
            $files = $input['image'];
            if ($files) {
                $destinationPath    = 'uploads/attachment/users/'; // The destination were you store the document.
                if(!(file_exists(public_path('/uploads/attachment/users/'))))
                {
                    File::makeDirectory($destinationPath, $mode = 0777, true, true);
                }
                $filename           = $files->getClientOriginalName(); // Original file name that the end user used for it.
                $mime_type          = $files->getMimeType(); // Gets this example image/png
                $extension          = $files->getClientOriginalExtension(); // The original extension that the user used example .jpg or .png.
                $filename           = time().'-'.$filename; // random file name to replace original
                $upload_success     = $files->move($destinationPath, $filename); // Now we move the file to its new home.
                $user->image = $destinationPath.'/'.$filename;
            }            
        }
        $user->save();
        \Session::flash('success','User berhasil di update');
        return redirect("users/");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::find($id);
        if(!is_null($user->image)){
            unlink($user->image);                
        }
        $user->delete();
        \Session::flash('success','User berhasil di dalete');

        return redirect("users/");
    }
}

resources/views/users/create.blade.php
@extends('layouts.app')

@section('content')
<!-- Basic Form Elements -->
<section class="panel">
    <div class="panel-heading">
        <h3>Tambah User</h3>
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-lg-12">
                <div class="margin-bottom-50">
                    <h4>Form User</h4>
                    <br />
                    <!-- Horizontal Form -->                    
                    <form class="form-horizontal" role="form" method="POST" action="{{ url('users') }}" enctype="multipart/form-data">
                         @csrf
                        <div class="form-group row">
                            <div class="col-md-3">
                                <label class="form-control-label" for="l0">Nama User</label>
                            </div>
                            <div class="col-md-9">
                                <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name"  placeholder="Input Name" required autofocus>

                                @if ($errors->has('name'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>  
                        <div class="form-group row">
                            <div class="col-md-3">
                                <label class="form-control-label" for="l0">Tipe User</label>
                            </div>
                            <div class="col-md-9">
                                <select id="user_type_id" type="text" class="selectpicker form-control{{ $errors->has('user_type_id') ? ' is-invalid' : '' }}" name="user_type_id"  placeholder="Input user_type_id" data-live-search="true" required autofocus>
                                    <option>Pilih Tipe User</option>
                                    @foreach ($user_types as $p)
                                    <option value="{{ $p->id }}">{{ $p->name }}</option>
                                    @endforeach
                                </select>

                                @if ($errors->has('user_type_id'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('user_type_id') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-md-3">
                                <label class="form-control-label" for="l0">Gambar User</label>
                            </div>
                            <div class="col-md-9">
                                <input id="image" type="file" class="form-control{{ $errors->has('image') ? ' is-invalid' : '' }}" name="image"  placeholder="Input Gambar User" autofocus>

                                @if ($errors->has('image'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('image') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-md-3">
                                <label class="form-control-label" for="l2">Email Address</label>
                            </div>
                            <div class="col-md-9">
                                <div class="input-group">
                                    <span class="input-group-addon">
                                        <i class="icmn-mail2"></i>
                                    </span>
                                    <input id="l2" type="text" class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" name="email"  placeholder="Email Address" required autofocus>

                                    @if ($errors->has('email'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('email') }}</strong>
                                        </span>
                                    @endif

                                </div>
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-md-3">
                                <label class="form-control-label" for="l3">Password</label>
                            </div>
                            <div class="col-md-9">
                                <div class="input-group">
                                    <input id="l3" type="password" class="form-control{{ $errors->has('password') ? ' is-invalid' : '' }}" name="password"  placeholder="Input Password" required autofocus>
                                    <span class="input-group-addon">
                                        <i class="icmn-key"></i>
                                    </span>
                                </div>
                            </div>
                        </div> 
                        <div class="form-group row">
                            <div class="col-md-3">
                                <label class="form-control-label" for="l3">Confirm Password</label>
                            </div>
                            <div class="col-md-9">
                                <div class="input-group">                                    
                                    <input id="l4" type="password" class="form-control{{ $errors->has('password') ? ' is-invalid' : '' }}" name="password-confirm"  placeholder="Confirm Password" required autofocus>
                                    <span class="input-group-addon">
                                        <i class="icmn-key"></i>
                                    </span>
                                </div>
                            </div>
                        </div>                        
                         <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Create') }}
                                </button>
                                <a class="btn btn-success" href="/users">Back</a>
                            </div>
                        </div>
                    </form>
                    <!-- End Horizontal Form -->
                </div>
            </div>
        </div>        
</section>
<!-- End -->
@endsection

resources/views/users/edit.blade.php
@extends('layouts.app')

@section('content')
<!-- Basic Form Elements -->
<section class="panel">
    <div class="panel-heading">
        <h3>Edit Data User</h3>
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-lg-12">
                <div class="margin-bottom-50">
                    <h4>Form User</h4>
                    <br />
                    <!-- Horizontal Form -->                    
                    <form class="form-horizontal" role="form" method="POST" action="{{ route('users.update', $user->id) }}" enctype="multipart/form-data">
                            @csrf
                            @method('PUT')
                        <input type="hidden" name="id" value="{{ $user->id }}">
                        <div class="form-group row">
                            <div class="col-md-3">
                                <label class="form-control-label" for="l0">Nama User</label>
                            </div>
                            <div class="col-md-9">
                                <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name"  placeholder="Input Name" value="{{ $user->name }}" required autofocus>

                                @if ($errors->has('name'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>              
                        <div class="form-group row">
                            <div class="col-md-3">
                                <label class="form-control-label" for="l0">Tipe User</label>
                            </div>
                            <div class="col-md-9">
                                <select id="user_type_id" type="text" class="selectpicker form-control{{ $errors->has('user_type_id') ? ' is-invalid' : '' }}" name="user_type_id"  placeholder="Input user_type_id" data-live-search="true" required autofocus>
                                    <option>Pilih Tipe User</option>
                                    @foreach ($user_types as $p)
                                    @if($p->id == $user->user_type_id)
                                    <option value="{{ $p->id }}" selected="">{{ $p->name }}</option>
                                    @else
                                    <option value="{{ $p->id }}">{{ $p->name }}</option>
                                    @endif
                                    @endforeach
                                </select>

                                @if ($errors->has('user_type_id'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('user_type_id') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>  

                        @if($user->image)
                        <div class="form-group row">
                            <div class="col-md-3">
                                <label class="form-control-label" for="l0">Gambar Sidang</label>
                            </div>
                            <div class="col-md-4">
                                <img id="image" src="/{{$user->image}}" alt="{{$user->name}}" style="width:100%;max-width:300px">                                
                            </div>
                            <div class="col-md-3">
                                <input id="image" type="file" class="form-control{{ $errors->has('image') ? ' is-invalid' : '' }}" name="image"  placeholder="Input Gambar Sidang" autofocus>

                                @if ($errors->has('image'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('image') }}</strong>
                                    </span>
                                @endif
                            </div>
                            <div class="col-xs-2">
                                <p class="text-red">* Upload jika ingin merubah gambar User</p>
                                <p class="text-red">* Ukuran Maksimal File 1MB</p>
                                <p class="text-red">* Format File : jpeg, jpg, png</p>
                            </div>
                        </div>
                        @else
                        <div class="form-group row">
                            <div class="col-md-3">
                                <label class="form-control-label" for="l0">Gambar User</label>
                            </div>
                            <div class="col-md-7">
                                <input id="image" type="file" class="form-control{{ $errors->has('image') ? ' is-invalid' : '' }}" name="image"  placeholder="Input Gambar User" autofocus>

                                @if ($errors->has('image'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('image') }}</strong>
                                    </span>
                                @endif
                            </div>
                            <div class="col-xs-2">
                                <p class="text-red">* Upload jika ingin merubah gambar User</p>
                                <p class="text-red">* Ukuran Maksimal File 1MB</p>
                                <p class="text-red">* Format File : jpeg, jpg, png</p>
                            </div>
                        </div>
                        @endif

                        <div class="form-group row">
                            <div class="col-md-3">
                                <label class="form-control-label" for="l2">Email Address</label>
                            </div>
                            <div class="col-md-9">
                                <div class="input-group">
                                    <span class="input-group-addon">
                                        <i class="icmn-mail2"></i>
                                    </span>
                                    <input id="l2" type="text" class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" name="email"  placeholder="Email Address" value="{{ $user->email }}" required autofocus>

                                    @if ($errors->has('email'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('email') }}</strong>
                                        </span>
                                    @endif

                                </div>
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-md-3">
                                <label class="form-control-label" for="l3">Password</label>
                            </div>
                            <div class="col-md-9">
                                <div class="input-group">
                                    <input id="l3" type="password" class="form-control{{ $errors->has('password') ? ' is-invalid' : '' }}" name="password"  placeholder="Input Password"  autofocus>
                                    <span class="input-group-addon">
                                        <i class="icmn-key"></i>
                                    </span>
                                </div>
                            </div>
                        </div> 
                        <div class="form-group row">
                            <div class="col-md-3">
                                <label class="form-control-label" for="l3">Confirm Password</label>
                            </div>
                            <div class="col-md-9">
                                <div class="input-group">                                    
                                    <input id="l4" type="password" class="form-control{{ $errors->has('password') ? ' is-invalid' : '' }}" name="password-confirm"  placeholder="Confirm Password"  autofocus>
                                    <span class="input-group-addon">
                                        <i class="icmn-key"></i>
                                    </span>
                                </div>
                            </div>
                        </div>                        
                         <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Update') }}
                                </button>
                                <a class="btn btn-success" href="/users">Back</a>
                            </div>
                        </div>
                    </form>
                    <!-- End Horizontal Form -->
                </div>
            </div>
        </div>        
</section>
<!-- End -->
@endsection

resources/views/users/index.blade.php
@extends('layouts.app')

@section('content')
<section class="page-content">
<div class="page-content-inner">    
    <!--  -->
    <section class="panel">
        <div class="panel-heading">
            <h3>
            Mengelola Pengguna
            </h3>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-lg-12">
                    @if ($message = Session::get('success'))
                    <div class="alert alert-success" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <strong>{{ $message }}</strong>
                    </div>
                    @endif
                    <div class="col-md-4">
                        <a href="/users/create" class="btn btn-primary">
                            Tambah User
                        </a>
                    </div>
                    
                    <div class="col-xs-12">&nbsp;</div>                    
                    <div class="margin-bottom-50">
                        <table class="table table-hover nowrap" id="example1" width="100%">
                            <thead>
                              <tr>
                                <th>Nama</th>
                                <th>Email</th>
                                <th>Tipe User</th>
                                <th width="15%">Aksi</th>
                              </tr>
                            <tbody>
                                @foreach($users as $user)
                                <tr>
                                    <td>{{$user->name}}</td>
                                    <td>{{$user->email}}</td>
                                    <td>{{$user->user_type ? $user->user_type->name : "" }}</td>
                                    <td> 
                                        <a class='btn btn-primary btn-xs' href='{{url('users/'.$user->id.'/edit')}}'>Edit</a>
                                        <a class='btn btn-danger btn-xs open-confirm-hapus' onclick="return confirm('Anda Yakin Hapus Data Ini?')" href='{{url('users/delete')}}/{{$user->id}}'>Delete</a>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- End  -->

</div>

<!-- Page Scripts -->
<script>
    $(function(){
        $('.datepicker').datetimepicker({
            format:  "YYYY-MM-DD"
        });
    });
</script>
<!-- End Page Scripts -->
</section>
@endsection