routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', 'App\Http\Controllers\HomeController@index')->name('home');
// Auth::routes();

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return redirect('/');
})->name('dashboard');

// route users
Route::resource('users', 'App\Http\Controllers\UsersController');    
Route::get('/users/delete/{id}', 'App\Http\Controllers\UsersController@destroy');

// route user_types
Route::resource('user_types', 'App\Http\Controllers\UserTypesController');    
Route::get('/user_types/delete/{id}', 'App\Http\Controllers\UserTypesController@destroy');

// route meetings
Route::resource('meetings', 'App\Http\Controllers\MeetingsController');    
Route::get('/meetings/delete/{id}', 'App\Http\Controllers\MeetingsController@destroy');
Route::get('/meetings/create_document_meetings/{id}', 'App\Http\Controllers\MeetingsController@create_document_meetings');
Route::post('/meetings/create_document_meetings', 'App\Http\Controllers\MeetingsController@store_document_meetings');
Route::post('/meetings/update_document_report', 'App\Http\Controllers\MeetingsController@update_document_report');
Route::get("/meetings/download_document_meetings/{id}", "App\Http\Controllers\MeetingsController@download_document_meetings");
Route::get("/meetings/delete_meeting_document/{id}", "App\Http\Controllers\MeetingsController@delete_meeting_document");
Route::get('/meetings/{id}/export_excel', 'App\Http\Controllers\MeetingsController@export_excel');
Route::get("/meetings/download_document_report/{id}", "App\Http\Controllers\MeetingsController@download_document_report");

// route meetings
Route::resource('meeting_agendas', 'App\Http\Controllers\MeetingAgendasController');    
Route::get('/meeting_agendas/delete/{id}', 'App\Http\Controllers\MeetingAgendasController@destroy');

// route Comments
Route::resource('comments', 'App\Http\Controllers\CommentsController');    
Route::get('/comments/delete/{id}', 'App\Http\Controllers\CommentsController@destroy');
Route::post('/comments/update_meeting_agenda', 'App\Http\Controllers\CommentsController@update_meeting_agenda');

app/Models/Meeting.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Meeting extends Model
{
    use HasFactory;

    public function agendas()
    {
        return $this->hasMany('App\Models\MeetingAgenda')->orderBy('created_at');
    }

    public function document_meetings()
    {
        return $this->hasMany('App\Models\MeetingDocument');
    }
}

app/Http/Controllers/MeetingsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Meeting;
use App\Models\MeetingDocument;
use File;
use View;
use Maatwebsite\Excel\Facades\Excel;
use App\Exports\MeetingExport;
use Carbon\Carbon;

class MeetingsController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $meetings = Meeting::orderBy('date', 'desc')->get();
        return view("meetings.index",compact(["meetings"]));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $meetings = Meeting::all();
        return view("meetings.create",compact(["meetings"]));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $count_meeting = Meeting::count();
        $date_now = Carbon::now();

        $input = $request->all();
        $meeting = new Meeting;
        $meeting->name = $input['name'];
        $meeting->description = $input['description'];
        $meeting->ordering = $count_meeting + 1;
        if(isset($input['date'])){
            $meeting->date = date("Y-m-d", strtotime($input['date']));
        }else{
            $meeting->date = date('Y-m-d', strtotime($date_now));
        }
        if(isset($input['image'])){
            $files = $input['image'];
            if ($files) {
                $destinationPath    = 'uploads/attachment/meetings/'; // The destination were you store the document.
                if(!(file_exists(public_path('/uploads/attachment/meetings/'))))
                {
                    File::makeDirectory($destinationPath, $mode = 0777, true, true);
                }
                $filename           = $files->getClientOriginalName(); // Original file name that the end user used for it.
                $mime_type          = $files->getMimeType(); // Gets this example image/png
                $extension          = $files->getClientOriginalExtension(); // The original extension that the user used example .jpg or .png.
                $filename           = time().'-'.$filename; // random file name to replace original
                $upload_success     = $files->move($destinationPath, $filename); // Now we move the file to its new home.
                $meeting->image = $destinationPath.'/'.$filename;
            }
        }        
        $meeting->created_by = $input['created_by'];
        $meeting->save();

            $i = 0;
            $count_looping = $input['count_looing_product_image'];
            for ($x = 0; $x < $count_looping; $x++) {                
                $meeting_document = new MeetingDocument;
                $meeting_document->meeting_id = $meeting->id;
                $meeting_document->name = $input['name_document'][$i];
                // upload image
                if(isset($input['document'][$i])){
                    $files = $input['document'][$i];
                    if ($files) {
                        $destinationPath    = 'uploads/attachment/meeting_documents/'; // The destination were you store the document.
                        if(!(file_exists(public_path('/uploads/attachment/meeting_documents/'))))
                        {
                            File::makeDirectory($destinationPath, $mode = 0777, true, true);
                        }
                        $filename           = $files->getClientOriginalName(); // Original file name that the end user used for it.
                        $mime_type          = $files->getMimeType(); // Gets this example image/png
                        $extension          = $files->getClientOriginalExtension(); // The original extension that the user used example .jpg or .png.
                        $filename           = time().'-'.$filename; // random file name to replace original
                        $upload_success     = $files->move($destinationPath, $filename); // Now we move the file to its new home.
                        $meeting_document->document = $destinationPath.'/'.$filename;
                    }
                }
                $meeting_document->save();
                $i++;
            }
        
        \Session::flash('success','Sidang berhasil dibuat');
        return redirect("meetings/");
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $meeting = Meeting::find($id);
        return view("meetings.show",compact(["meeting"]));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {        
        $meeting = Meeting::find($id);
        return view("meetings.edit",compact(["meeting"]));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $input = $request->all();
        $date_now = Carbon::now();
        
        $meeting = Meeting::find($id);
        $meeting->name = $input['name'];
        $meeting->description = $input['description'];
        if(isset($input['date'])){
            $meeting->date = date("Y-m-d", strtotime($input['date']));
        }else{
            $meeting->date = date('Y-m-d', strtotime($date_now));
        }
        $meeting->updated_by = $input['updated_by'];

        if ($request->file('image')) {
            if(!is_null($meeting->image)){
                unlink($meeting->image);                
            }
            $files = $input['image'];
            if ($files) {
                $destinationPath    = 'uploads/attachment/meetings/'; // The destination were you store the document.
                if(!(file_exists(public_path('/uploads/attachment/meetings/'))))
                {
                    File::makeDirectory($destinationPath, $mode = 0777, true, true);
                }
                $filename           = $files->getClientOriginalName(); // Original file name that the end user used for it.
                $mime_type          = $files->getMimeType(); // Gets this example image/png
                $extension          = $files->getClientOriginalExtension(); // The original extension that the user used example .jpg or .png.
                $filename           = time().'-'.$filename; // random file name to replace original
                $upload_success     = $files->move($destinationPath, $filename); // Now we move the file to its new home.
                $meeting->image = $destinationPath.'/'.$filename;
            }            
        }
        
        if ($request->file('document_report')) {
            if(!is_null($meeting->document_report)){
                unlink($meeting->document_report);                
            }
            $files = $input['document_report'];
            if ($files) {
                $destinationPath    = 'uploads/attachment/meetings/'; // The destination were you store the document.
                if(!(file_exists(public_path('/uploads/attachment/meetings/'))))
                {
                    File::makeDirectory($destinationPath, $mode = 0777, true, true);
                }
                $filename           = $files->getClientOriginalName(); // Original file name that the end user used for it.
                $mime_type          = $files->getMimeType(); // Gets this example image/png
                $extension          = $files->getClientOriginalExtension(); // The original extension that the user used example .jpg or .png.
                $filename           = time().'-'.$filename; // random file name to replace original
                $upload_success     = $files->move($destinationPath, $filename); // Now we move the file to its new home.
                $meeting->document_report = $destinationPath.'/'.$filename;
            }            
        }

        $meeting->save();
        \Session::flash('success','Sidang berhasil di update');
        return redirect("meetings/");
    }

    public function export_excel($id)
	{
        $meeting = Meeting::find($id);
        $dg = array();
        $templateProcessor = new \PhpOffice\PhpWord\TemplateProcessor(public_path('tamplate/TABEL_POSISI_SIDANG.docx'));
        $templateProcessor->setValue("meeting_name",htmlspecialchars($meeting->name));

        $i = 0;
        foreach ($meeting->agendas as $agenda) {
            $comments = '';
            foreach ($agenda->comments as $comment) {
                $comments .= $comment->comment. ', ';   
            }
            $dg[] = ["name" => $agenda->name, "description" => $agenda->description, "konklusi" => $agenda->konklusi, "intervensi" => $agenda->intervensi, "comments" => $comments];
            $i = $i + 1;            
        }        

        $templateProcessor->cloneRow('name', count($dg));  

        $parser = new \HTMLtoOpenXML\Parser();
        for($i = 1; $i <= count($dg); $i++){           
            $templateProcessor->setValue("no#".$i, htmlspecialchars($i));
            $templateProcessor->setValue("name#".$i, htmlspecialchars($dg[$i-1]["name"]));
            $description = $parser->fromHTML($dg[$i-1]["description"]);
            $templateProcessor->setValue("description#".$i, strip_tags(htmlspecialchars_decode($description)));

            $comments = $parser->fromHTML($dg[$i-1]["comments"]);

resources/views/meetings/create_document.blade.php
@extends('layouts.app')

@section('content')
<!-- Basic Form Elements -->
<section class="panel">
    <div class="panel-heading">
        <h3>Tambah Dokument Sidang {{$meeting->name}}</h3>
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-lg-12">
                <div class="margin-bottom-50">
                    <h4>Form Dokument Sidang</h4>
                    <br />
                    <!-- Horizontal Form -->                    
                    <form class="form-horizontal" role="form" method="POST" action="{{ url('/meetings/create_document_meetings') }}" enctype="multipart/form-data">
                         @csrf
                        <input type="hidden" class="form-control" name="created_by" id="created_by" value="{{ Auth::user()->id }}">
                        <input type="hidden" class="form-control" name="meeting_id" id="meeting_id" value="{{$meeting->id}}">
                        <div class="form-group row">
                            <div class="col-md-3">
                                <label class="form-control-label" for="l0">Nama Dokumen</label>
                            </div>
                            <div class="col-md-9">
                                <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name"  placeholder="Input Nama Dokumen" autofocus>

                                @if ($errors->has('name'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col-md-3">
                                <label class="form-control-label" for="l0">Dokumen Sidang {{$meeting->name}}</label>
                            </div>
                            <div class="col-md-9">
                            <input type="file" class="form-control" id="document" name="document" data-max-size="2097152" placeholder="Upload File Gambar" required="">

                                @if ($errors->has('document'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('document') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                                              
                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Create') }}
                                </button>
                                <a class="btn btn-success" href="/meetings/{{$meeting->id}}">Back</a>
                            </div>
                        </div>
                    </form>
                    <!-- End Horizontal Form -->
                </div>
            </div>
        </div>        
</section>
<!-- End -->

<script>
    $(function(){
        $('.datepicker-only-init').datetimepicker({
            widgetPositioning: {
                horizontal: 'left'
            },
            icons: {
                time: "fa fa-clock-o",
                date: "fa fa-calendar",
                up: "fa fa-arrow-up",
                down: "fa fa-arrow-down"
            },
            format: 'LL'
        });

        var document = $('#document');
        var maxSize = document.data('max-size');
        $("form").submit(function(){
            if(document.val() != '' && document.get(0).files[0].size>maxSize){
                alert('file dokumen sidang melebihi batas ' +maxSize+ ' bytes');
                return false;
            }      
        });
    })
</script>
@endsection

resources/views/meetings/edit.blade.php
@extends('layouts.app')

@section('content')
<!-- Basic Form Elements -->
<section class="panel">
    <div class="panel-heading">
        <h3>Edit Sidang</h3>
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-lg-12">
                <div class="margin-bottom-50">
                    <h4>Form Sidang</h4>
                    <br />
                    <!-- Horizontal Form -->                    
                    <form class="form-horizontal" role="form" method="POST" action="{{ route('meetings.update', $meeting->id) }}" enctype="multipart/form-data">
                        @csrf
                        @method('PUT')
                        <input type="hidden" class="form-control" name="updated_by" id="updated_by" value="{{ Auth::user()->id }}">
                        <div class="form-group row">
                            <div class="col-md-3">
                                <label class="form-control-label" for="l0">Nama Sidang</label>
                            </div>
                            <div class="col-md-9">
                                <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name"  placeholder="Input Nama Sidang" value="{{$meeting->name}}" required autofocus>

                                @if ($errors->has('name'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        @if($meeting->image)
                        <div class="form-group row">
                            <div class="col-md-3">
                                <label class="form-control-label" for="l0">Gambar Sidang</label>
                            </div>
                            <div class="col-md-4">
                                <img id="image" src="/{{$meeting->image}}" alt="{{$meeting->name}}" style="width:100%;max-width:300px">                                
                            </div>
                            <div class="col-md-3">
                                <input id="image" type="file" class="form-control{{ $errors->has('image') ? ' is-invalid' : '' }}" name="image" data-max-size="2097152"  placeholder="Input Gambar Sidang" autofocus>

                                @if ($errors->has('image'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('image') }}</strong>
                                    </span>
                                @endif
                            </div>
                            <div class="col-xs-2">
                                <p class="text-red">* Upload jika ingin merubah gambar sidang</p>
                                <p class="text-red">* Ukuran Maksimal File 2MB</p>
                                <p class="text-red">* Format File : jpeg, jpg, png</p>
                            </div>
                        </div>
                        @else
                        <div class="form-group row">
                            <div class="col-md-3">
                                <label class="form-control-label" for="l0">Gambar Sidang</label>
                            </div>
                            <div class="col-md-7">
                                <input id="image" type="file" class="form-control{{ $errors->has('image') ? ' is-invalid' : '' }}" name="image" data-max-size="2097152"  placeholder="Input Gambar Sidang" autofocus>

                                @if ($errors->has('image'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('image') }}</strong>
                                    </span>
                                @endif
                            </div>
                            <div class="col-xs-2">
                                <p class="text-red">* Upload jika ingin merubah gambar sidang</p>
                                <p class="text-red">* Ukuran Maksimal File 2MB</p>
                                <p class="text-red">* Format File : jpeg, jpg, png</p>
                            </div>
                        </div>
                        @endif

                        @if($meeting->document_report)
                        <div class="form-group row">
                            <div class="col-md-3">
                                <label class="form-control-label" for="l0">Laporan Sidang</label>
                            </div>
                            <div class="col-md-2">                                
                                <a href="{{url('/meetings/download_document_report/'.$meeting->id)}}" class="btn btn-info">
                                    Download
                                </a>
                            </div>
                            <div class="col-md-5">
                                <input id="document_report" type="file" class="form-control{{ $errors->has('document_report') ? ' is-invalid' : '' }}" name="document_report" data-max-size="2097152"  placeholder="Input Gambar Sidang" autofocus>

                                @if ($errors->has('document_report'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('document_report') }}</strong>
                                    </span>
                                @endif
                            </div>
                            <div class="col-xs-2">
                                <p class="text-red">* Upload jika ingin merubah Laporan sidang</p>
                                <p class="text-red">* Ukuran Maksimal File 2MB</p>
                                <p class="text-red">* Format File : pdf, docx</p>
                            </div>
                        </div>
                        @else
                        <div class="form-group row">
                            <div class="col-md-3">
                                <label class="form-control-label" for="l0">Laporan Sidang</label>
                            </div>
                            <div class="col-md-7">
                                <input id="document_report" type="file" class="form-control{{ $errors->has('document_report') ? ' is-invalid' : '' }}" name="document_report" data-max-size="2097152"  placeholder="Input Gambar Sidang" autofocus>

                                @if ($errors->has('document_report'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('document_report') }}</strong>
                                    </span>
                                @endif
                            </div>
                            <div class="col-xs-2">
                                <p class="text-red">* Ukuran Maksimal File 2MB</p>
                                <p class="text-red">* Format File : pdf, docx</p>
                            </div>
                        </div>
                        @endif

                        <div class="form-group row">
                            <div class="col-md-3">
                                <label class="form-control-label" for="l0">Keterangan Sidang</label>
                            </div>
                            <div class="col-md-9">
                                <textarea class="form-control summernote" id="description" name="description" placeholder="Input Keterangan Sidang" rows="3" id="l15">{{$meeting->description}}</textarea>
                                @if ($errors->has('description'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('description') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>                       

                        <div class="form-group row">
                            <div class="col-md-3">
                                <label class="form-control-label" for="l0">Tanggal Sidang</label>
                            </div>
                            <div class="col-md-9">
                                <div class="form-group">
                                    <label class="input-group datepicker-only-init">
                                        <input type="text" id="date"  class="form-control datepicker-only-init" name="date" value="{{$meeting->date}}" placeholder="Tanggal Sidang"  autofocus/>
                                        <span class="input-group-addon">
                                            <i class="icmn-calendar"></i>
                                        </span>
                                    </label>
                                </div>
                            </div>
                        </div>
                                              
                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Update') }}
                                </button>
                                <a class="btn btn-success" href="/meetings">Back</a>
                            </div>
                        </div>
                    </form>
                    <!-- End Horizontal Form -->
                </div>
            </div>
        </div>        
</section>
<!-- End -->

<script>
    $(function(){
        $('.datepicker-only-init').datetimepicker({
            widgetPositioning: {
                horizontal: 'left'
            },
            icons: {
                time: "fa fa-clock-o",
                date: "fa fa-calendar",
                up: "fa fa-arrow-up",
                down: "fa fa-arrow-down"
            },
            format: 'YYYY-MM-DD'
        });

        $('.summernote').summernote({
            height: 350
        });

        var image = $('#image');        
        var maxSize = image.data('max-size');
        var document = $('#document_report');
        var maxSizeDocument = document.data('max-size');
        $("form").submit(function(){            
            if(image.val() != '' && image.get(0).files[0].size>maxSize){
                alert('file gambar sidang melebihi batas ' +maxSize+ ' bytes');
                return false;
            }else if(document.val() != '' && document.get(0).files[0].size>maxSizeDocument){
                alert('file dokumen repot melebihi batas ' +maxSize+ ' bytes');
                return false;
            }      
        });
    })
</script>
@endsection

resources/views/meetings/excel.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>Export Laporan Excel Pada Laravel</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
 
	<div class="container">
		<center>
			<h4>KERTAS POSISI SIDANG {{$meeting->name}}</h4>
		</center>	
		
		<table class='table table-bordered'>
			<thead>
				<tr>
					<th>No</th>
					<th>Agenda</th>
					<th>Konklusi</th>
					<th>Intervensi</th>
				</tr>
			</thead>
			<tbody>
				@php $i=1 @endphp
				@foreach($meeting->agendas as $s)
				<tr>
					<td>{{ $i++ }}</td>
					<td>{{$s->name}}</td>
					<td>{!!$s->konklusi!!}</td>
					<td>{!!$s->intervensi!!}</td>
				</tr>
				@endforeach
			</tbody>
		</table>
	</div>
 
</body>
</html>