routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', 'App\Http\Controllers\HomeController@index')->name('home');
// Auth::routes();

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return redirect('/');
})->name('dashboard');

// route users
Route::resource('users', 'App\Http\Controllers\UsersController');    
Route::get('/users/delete/{id}', 'App\Http\Controllers\UsersController@destroy');

// route user_types
Route::resource('user_types', 'App\Http\Controllers\UserTypesController');    
Route::get('/user_types/delete/{id}', 'App\Http\Controllers\UserTypesController@destroy');

// route meetings
Route::resource('meetings', 'App\Http\Controllers\MeetingsController');    
Route::get('/meetings/delete/{id}', 'App\Http\Controllers\MeetingsController@destroy');
Route::get('/meetings/create_document_meetings/{id}', 'App\Http\Controllers\MeetingsController@create_document_meetings');
Route::post('/meetings/create_document_meetings', 'App\Http\Controllers\MeetingsController@store_document_meetings');
Route::post('/meetings/update_document_report', 'App\Http\Controllers\MeetingsController@update_document_report');
Route::get("/meetings/download_document_meetings/{id}", "App\Http\Controllers\MeetingsController@download_document_meetings");
Route::get("/meetings/delete_meeting_document/{id}", "App\Http\Controllers\MeetingsController@delete_meeting_document");
Route::get('/meetings/{id}/export_excel', 'App\Http\Controllers\MeetingsController@export_excel');
Route::get("/meetings/download_document_report/{id}", "App\Http\Controllers\MeetingsController@download_document_report");

// route meetings
Route::resource('meeting_agendas', 'App\Http\Controllers\MeetingAgendasController');    
Route::get('/meeting_agendas/delete/{id}', 'App\Http\Controllers\MeetingAgendasController@destroy');

// route Comments
Route::resource('comments', 'App\Http\Controllers\CommentsController');    
Route::get('/comments/delete/{id}', 'App\Http\Controllers\CommentsController@destroy');
Route::post('/comments/update_meeting_agenda', 'App\Http\Controllers\CommentsController@update_meeting_agenda');

app/Models/MeetingAgenda.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class MeetingAgenda extends Model
{
    use HasFactory;

    public function comments()
    {
        return $this->hasMany('App\Models\Comment');
    }

    public function meeting()
    {
        return $this->belongsTo('App\Models\Meeting');
    }
}

app/Http/Controllers/MeetingAgendasController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\MeetingAgenda;

class MeetingAgendasController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view("meeting_agendas.create");
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $input = $request->all();
        $meeting_agenda = new MeetingAgenda;
        $meeting_agenda->meeting_id = $input['meeting_id'];
        $meeting_agenda->name = $input['name'];
        $meeting_agenda->description = $input['description'];
        // $meeting_agenda->ordering = $input['ordering'];
        $meeting_agenda->konklusi = $input['konklusi'];
        $meeting_agenda->intervensi = $input['intervensi'];
        $meeting_agenda->created_by = $input['created_by'];
        $meeting_agenda->save();
        \Session::flash('success','Agenda berhasil dibuat');
        return redirect("meetings/".$meeting_agenda->meeting_id);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $meeting_agenda = MeetingAgenda::find($id);
        return view("meeting_agendas.show",compact(["meeting_agenda"]));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $meeting_agenda = MeetingAgenda::find($id);
        return view("meeting_agendas.edit",compact(["meeting_agenda"]));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $input = $request->all();
        $meeting_agenda = MeetingAgenda::find($id);
        $meeting_agenda->meeting_id = $input['meeting_id'];
        $meeting_agenda->name = $input['name'];
        $meeting_agenda->description = $input['description'];
        // $meeting_agenda->ordering = $input['ordering'];
        $meeting_agenda->konklusi = $input['konklusi'];
        $meeting_agenda->intervensi = $input['intervensi'];
        $meeting_agenda->updated_by = $input['updated_by'];
        $meeting_agenda->save();
        \Session::flash('success','Agenda berhasil diupdate');
        return redirect("meetings/".$meeting_agenda->meeting_id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $meeting_agenda = MeetingAgenda::find($id);
        $meeting_agenda->delete();
        \Session::flash('success','Agenda berhasil di Hapus');

        return redirect("meetings/".$meeting_agenda->meeting_id);
    }
}

resources/views/meeting_agendas/create.blade.php
@extends('layouts.app')

@section('content')
<!-- Basic Form Elements -->
<section class="panel">
    <div class="panel-heading">
        <h3>Tambah Sidang</h3>
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-lg-12">
                <div class="margin-bottom-50">
                    <h4>Form Sidang</h4>
                    <br />
                    <!-- Horizontal Form -->                    
                    <form class="form-horizontal" role="form" method="POST" action="{{ url('meeting_agendas') }}" enctype="multipart/form-data">
                         @csrf
                        <input type="hidden" class="form-control" name="created_by" id="created_by" value="{{ Auth::user()->id }}">
                        <input type="hidden" class="form-control" name="meeting_id" id="meeting_id" value="{{ request()->get('meeting_id') }}">
                        <div class="form-group row">
                            <div class="col-md-3">
                                <label class="form-control-label" for="l0">Agenda</label>
                            </div>
                            <div class="col-md-9">
                                <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name"  placeholder="Input Agenda" autofocus>

                                @if ($errors->has('name'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col-md-3">
                                <label class="form-control-label" for="l0">Keterangan Agenda</label>
                            </div>
                            <div class="col-md-9">
                                <textarea class="form-control summernote" id="description" name="description" placeholder="Input Keterangan" rows="3" id="l15"></textarea>
                                @if ($errors->has('description'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('description') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>                        

                        <div class="form-group row">
                            <div class="col-md-3">
                                <label class="form-control-label" for="l0">Konklusi</label>
                            </div>
                            <div class="col-md-9">
                                <textarea class="form-control summernote" id="konklusi" name="konklusi" placeholder="Input Konklusi" rows="3" id="l15"></textarea>
                                @if ($errors->has('konklusi'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('konklusi') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col-md-3">
                                <label class="form-control-label" for="l0">Intervensi</label>
                            </div>
                            <div class="col-md-9">
                                <textarea class="form-control summernote" id="intervensi" name="intervensi" placeholder="Input Intervensi" rows="3" id="l15"></textarea>
                                @if ($errors->has('intervensi'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('intervensi') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                                              
                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Create') }}
                                </button>
                                <a class="btn btn-success" href="/meetings/{{ request()->get('meeting_id') }}">Back</a>
                            </div>
                        </div>
                    </form>
                    <!-- End Horizontal Form -->
                </div>
            </div>
        </div>        
</section>
<!-- End -->

<script>
    $(function(){
        $('.datepicker-only-init').datetimepicker({
            widgetPositioning: {
                horizontal: 'left'
            },
            icons: {
                time: "fa fa-clock-o",
                date: "fa fa-calendar",
                up: "fa fa-arrow-up",
                down: "fa fa-arrow-down"
            },
            format: 'LL'
        });

        $('.summernote').summernote({
            height: 350
        });
    })
</script>
@endsection

resources/views/meeting_agendas/edit.blade.php
@extends('layouts.app')

@section('content')
<!-- Basic Form Elements -->
<section class="panel">
    <div class="panel-heading">
        <h3>Edit Agenda</h3>
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-lg-12">
                <div class="margin-bottom-50">
                    <h4>Form Agenda</h4>
                    <br />
                    <!-- Horizontal Form -->                    
                    <form class="form-horizontal" role="form" method="POST" action="{{ route('meeting_agendas.update', $meeting_agenda->id) }}" enctype="multipart/form-data">
                         @csrf
                         @method('PUT')
                        <input type="hidden" class="form-control" name="updated_by" id="updated_by" value="{{ Auth::user()->id }}">
                        <input type="hidden" class="form-control" name="meeting_id" id="meeting_id" value="{{ $meeting_agenda->meeting_id }}">
                        <div class="form-group row">
                            <div class="col-md-3">
                                <label class="form-control-label" for="l0">Agenda</label>
                            </div>
                            <div class="col-md-9">
                                <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name"  placeholder="Input Agenda" value="{{$meeting_agenda->name}}" autofocus>

                                @if ($errors->has('name'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col-md-3">
                                <label class="form-control-label" for="l0">Keterangan Agenda</label>
                            </div>
                            <div class="col-md-9">
                                <textarea class="form-control summernote" id="description" name="description" placeholder="Input Keterangan" rows="3" id="l15">{{$meeting_agenda->description}}</textarea>
                                @if ($errors->has('description'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('description') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>                       

                        <div class="form-group row">
                            <div class="col-md-3">
                                <label class="form-control-label" for="l0">Konklusi</label>
                            </div>
                            <div class="col-md-9">
                                <textarea class="form-control summernote" id="konklusi" name="konklusi" placeholder="Input Konklusi" rows="3" id="l15">{{$meeting_agenda->konklusi}}</textarea>
                                @if ($errors->has('konklusi'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('konklusi') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col-md-3">
                                <label class="form-control-label" for="l0">Intervensi</label>
                            </div>
                            <div class="col-md-9">
                                <textarea class="form-control summernote" id="intervensi" name="intervensi" placeholder="Input Intervensi" rows="3" id="l15">{{$meeting_agenda->intervensi}}</textarea>
                                @if ($errors->has('intervensi'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('intervensi') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                                              
                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Update') }}
                                </button>
                                <a class="btn btn-success" href="/meetings/{{$meeting_agenda->meeting_id}}">Back</a>
                            </div>
                        </div>
                    </form>
                    <!-- End Horizontal Form -->
                </div>
            </div>
        </div>        
</section>
<!-- End -->

<script>
    $(function(){
        $('.datepicker-only-init').datetimepicker({
            widgetPositioning: {
                horizontal: 'left'
            },
            icons: {
                time: "fa fa-clock-o",
                date: "fa fa-calendar",
                up: "fa fa-arrow-up",
                down: "fa fa-arrow-down"
            },
            format: 'LL'
        });

        $('.summernote').summernote({
            height: 350
        });
    })
</script>
@endsection

resources/views/meeting_agendas/show.blade.php
@extends('layouts.app')

@section('content')
<!-- Basic Form Elements -->
<section class="panel">
    <div class="panel-heading">
        <h3>Edit Agenda</h3>
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-lg-12">
                <div class="margin-bottom-50">
                    <h4>Form Agenda</h4>
                    <br />
                    <!-- Horizontal Form -->                    
                    <form class="form-horizontal" role="form" method="POST" action="{{ route('meeting_agendas.update', $meeting_agenda->id) }}" enctype="multipart/form-data">
                         @csrf
                         @method('PUT')
                        <input type="hidden" class="form-control" name="created_by" id="created_by" value="{{ Auth::user()->id }}">
                        <input type="hidden" class="form-control" name="meeting_id" id="meeting_id" value="{{ $meeting_agenda->meeting_id }}">
                        <div class="form-group row">
                            <div class="col-md-3">
                                <label class="form-control-label" for="l0">Agenda</label>
                            </div>
                            <div class="col-md-9">
                                <p>{{$meeting_agenda->name}}</p>

                                @if ($errors->has('name'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col-md-3">
                                <label class="form-control-label" for="l0">Keterangan Agenda</label>
                            </div>
                            <div class="col-md-9">
                                <p>{!!$meeting_agenda->description!!}</p>
                                @if ($errors->has('description'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('description') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>                        

                        <div class="form-group row">
                            <div class="col-md-3">
                                <label class="form-control-label" for="l0">Konklusi</label>
                            </div>
                            <div class="col-md-9">
                                <p>{!!$meeting_agenda->konklusi!!}</p>
                                @if ($errors->has('konklusi'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('konklusi') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col-md-3">
                                <label class="form-control-label" for="l0">Intervensi</label>
                            </div>
                            <div class="col-md-9">
                                <p>{!!$meeting_agenda->intervensi!!}</p>
                                @if ($errors->has('intervensi'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('intervensi') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                                              
                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">                                
                                <a class='btn btn-success' href='{{url('comments/create?meeting_agenda_id='.$meeting_agenda->id)}}'>Komentar</a> 
                                <a class='btn btn-primary' href='{{url('meeting_agendas/'.$meeting_agenda->id.'/edit')}}'>Edit</a>
                                <a class='btn btn-danger open-confirm-hapus' onclick="confirm('Are you sure?')" href='{{url('meeting_agendas/delete')}}/{{$meeting_agenda->id}}'>Delete</a>
                                <a class="btn btn-success" href="/meetings/{{$meeting_agenda->meeting_id}}">Back</a>
                            </div>
                        </div>
                    </form>
                    <!-- End Horizontal Form -->
                </div>
            </div>
        </div>        
</section>
<!-- End -->

<script>
    $(function(){
       
    })
</script>
@endsection